### ISSUE TITLE
LuaJIT tracking

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#1891]
Tracking issue for landing https://github.com/envoyproxy/envoy/pull/1859 and follow ups:

- [ ] add msleep() API
- [x] clear route cache if header map is modified
- [ ] L4 filter
- [ ] cluster manager raw TCP connection API

**Comment by mattklein123** [comment]
I'm going to go ahead and close this as fixed. We are now opening issues for specific Lua features and can track that way.
