### ISSUE TITLE
v1 deprecation tracking

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#2832]
- [ ] https://groups.google.com/forum/#!topic/envoy-announce/Lb1QZcSclGQ
- [x] https://github.com/envoyproxy/envoy/issues/2100
- [x] https://github.com/envoyproxy/envoy/issues/2139
- [ ] https://github.com/envoyproxy/envoy/issues/5355

**Comment by srikailash** [comment]
@mattklein123, i can work on these issues.(as i see both the issues are tagged with beginner, would be appropriate to me). Thanks!

**Comment by PiotrSikora** [comment]
We don't have good story for deprecating `bind_to_port`. Should we promote it to v2 or should we migrate to `prefix_ranges` and `destination_port` from `FilterChainMatch` (not implemented yet)?

cc @htuch @kyessenov

**Comment by mattklein123** [comment]
@PiotrSikora re: removing v1 support, IMO this is just removing v1 config processing, not necessarily all of the "v1 deprecated" fields in the v2 config. I think we can keep those until we have a complete story for them?

**Comment by htuch** [comment]
Yeah, I think that would be alright, as long as we can drop having to maintain v1 config ingestion and the associated support overhead and translation code.

**Comment by PiotrSikora** [comment]
Please add #5355 to the list.

**Comment by mattklein123** [comment]
Done!
