### ISSUE TITLE
CI improvement tracking

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#5784]
*Description*:

This is a tracking issue for CI improvement, from what discussed in [last community meeting on 1/29](https://docs.google.com/document/d/1Yc4zkV-A_cC_R3C0u6D15WQAsRSxADs8p2l8UMMa4P4/edit#).

Target:
- At least one gcc build with full test suite for GCC compatibility
- CI on each PR runs under 45 mins vs currently ~2 hour for release run

AI:
- [x] 1. Add build profiling to existing CI pipeline and store in artifacts for analysis
- [x] 2. Investigate other resource provision: Other hosted CI services, GCP, etc 
- [x] 3. Use Clang for release #4158 
- [ ] 4. move remaining circleci jobs to azp.

Any suggestions are welcome.

Relevant Links:
#3741

**Comment by mattklein123** [comment]
@lizan one thought: Write now we build/test all extensions, both because we have a monolithic build, but also because I think one of the server tests must compile everything. One thought is whether we could potentially somehow use staged builds to maybe build the prod code and then fan out some of the extension tests into parallel jobs. I'm not sure if this would save time or not but once we do some profiling worth thinking about.

**Comment by mattklein123** [comment]
Calling this done for now. We can track individual issues as needed.
